# See https://github.com/apache/infrastructure-asfyaml/ for the configuration reference.

github:
  description: Apache Asyncband (Incubating) Website
  homepage: https://asyncband.apache.org/
  features:
    issues: true
    projects: false
    wiki: false
  labels:
    - asyncband
    - docusaurus
    - website
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false
  pull_requests:
    del_branch_on_merge: true
  rulesets:
    - name: Protect site branches
      type: branch
      branches:
        includes:
          - main
          - asf-site
      restrict_deletion: true
      restrict_force_push: true

staging:
  profile: ~
  whoami: asf-site
  autostage: site/*

publish:
  whoami: asf-site

notifications:
  commits: commits@asyncband.apache.org
  pullrequests: commits@asyncband.apache.org
  jobs: commits@asyncband.apache.org
